[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
    ignorecase = true
[remote "origin"]
    url = git@github.com:my_awesome_app
    fetch = +refs/heads/*:refs/remotes/origin/*
permalink: pretty